name: Java CI with Gradle

on:
  push:
    branches: [ Pipelines ]
  pull_request:
    branches: [ Pipelines ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.6.3
    
    - name: Set up JDK 16.0.2
      uses: actions/setup-java@v2.6.3
      with:
        java-version: 1.9

    - name: Build with Gradle
      uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
      with:
        arguments: build
