# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Gradle Package

on:
  # Trigger the workflow on push or pull request
  push:
    branches: [ Pipelines ]
  pull_request:
    branches: [ Pipelines ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'temurin'
        
    - name: Build with Gradle 
      working-directory: ./ChatAppBackend
      run: gradle wrapper --gradle-version 7.3.1
      
    - name: Run frontend tests
      working-directory: ./ChatAppFrontend
      run: npm run test:unit
