name: Java CI with Gradle

on:
  push:
    branches: [ Pipelines ]
  pull_request:
    branches: [ Pipelines ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'temurin'
        
    - name: Build with Gradle 
      working-directory: ./ChatAppBackend
      run: gradle wrapper --gradle-version 7.3.1
